export { Academy } from "./Academy/academy.jsx";
export { Login } from "./Login/login.jsx";
export { Registration } from "./Registration/registration.jsx";
export { Payments } from "./Payments/payments.jsx";
export { Notifications } from "./Notifications/notifications.jsx";
export { Statistics } from "./Statistics/statistics.jsx";
export { Help } from "./Help/help.jsx";
export { Settings } from "./Settings/settings.jsx";
export { Transactions } from "./Transactions/transactions.jsx";
